Add react cheatsheet
darkmatter18/cheatsheet pull request #165
Opened 2022-09-22 12:16 UTC by mehdibouaziz

HI! I noticed the React cheatsheet was missing, so I added the most recent one from FreeCodeCamp, with a link to the original article, plus alternative popular cheatsheets at the end.

2022-09-22 13:50 UTC, darkmatter18 commented
It's good. ✌🏻

2022-09-22 13:51 UTC, darkmatter18 requested changes
Can you add the link in the Readme

2022-09-22 14:02 UTC, mehdibouaziz commented
Done! Added the link to the new cheatsheet in the javascript README.

2022-09-24 01:49 UTC, darkmatter18 approved these changes

2022-09-24 01:49 UTC, merged